# Generated by Django 3.0 on 2021-03-04 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('porters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='Número da casa a ser visitada')),
                ('vehicle_plate', models.CharField(blank=True, max_length=7, null=True, verbose_name='Placa do veiculo')),
                ('arrival_time', models.DateTimeField(auto_now=True, verbose_name='Horario chegada')),
                ('departure_time', models.DateTimeField(blank=True, null=True, verbose_name='Horario Saida')),
                ('authorization_schedule', models.DateTimeField(blank=True, null=True, verbose_name='Horario Autorizacao')),
                ('responsible_resident', models.CharField(blank=True, max_length=200, verbose_name='Morador responsavel por autorizar a entrada do visitante')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='porters.Porters', verbose_name='Porteiro responsavel pelo registro')),
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'db_table': 'visitors',
            },
        ),
    ]
